// app/api/payroll/submit/route.ts
import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/client'
import { supabase as dataSupabase } from '@/lib/supabaseClient'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { location_id, pay_date, payroll_group, submitted_by, employees } = body

    console.log('📥 Payroll submission received:', {
      location_id,
      pay_date,
      payroll_group,
      employee_count: employees.length
    })

    // Validate required fields
    if (!location_id || !pay_date || !payroll_group || !submitted_by || !employees || employees.length === 0) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      )
    }

    // Get organization_id from the location
    const { data: locationData, error: locationError } = await dataSupabase
      .from('locations')
      .select('organization_id, name')
      .eq('id', location_id)
      .single()

    if (locationError || !locationData) {
      console.error('❌ Location not found:', locationError)
      return NextResponse.json(
        { error: 'Location not found' },
        { status: 404 }
      )
    }

    const organization_id = locationData.organization_id

    // Calculate totals
    const total_amount = employees.reduce((sum: number, emp: any) => sum + emp.amount, 0)
    const total_hours = employees.reduce((sum: number, emp: any) => sum + (emp.hours || 0), 0)
    const total_units = employees.reduce((sum: number, emp: any) => sum + (emp.units || 0), 0)
    const total_employees = employees.length

    console.log('💰 Calculated totals:', {
      total_amount,
      total_hours,
      total_units,
      total_employees
    })

    // 1. Insert into payroll_submissions table
    // Note: submission_number is auto-generated by database sequence
    const { data: submission, error: submissionError } = await dataSupabase
      .from('payroll_submissions')
      .insert({
        organization_id,
        location_id,
        pay_date,
        payroll_group,
        total_employees,
        total_hours,
        total_units,
        total_amount,
        status: 'pending',
        submitted_by,
        submitted_at: new Date().toISOString()
      })
      .select('id, submission_number')
      .single()

    if (submissionError) {
      console.error('❌ Submission insert error:', submissionError)
      return NextResponse.json(
        { error: 'Failed to create submission', details: submissionError.message },
        { status: 500 }
      )
    }

    console.log('✅ Submission created:', { id: submission.id, number: submission.submission_number })

    // 2. Insert into payroll_entries table
    const payrollEntries = employees.map((emp: any) => ({
      organization_id,
      submission_id: submission.id,
      employee_id: emp.employee_id,
      hours: emp.hours,
      units: emp.units,
      amount: emp.amount,
      notes: emp.notes
    }))

    const { error: entriesError } = await dataSupabase
      .from('payroll_entries')
      .insert(payrollEntries)

    if (entriesError) {
      console.error('❌ Entries insert error:', entriesError)
      
      // Rollback submission
      await dataSupabase
        .from('payroll_submissions')
        .delete()
        .eq('id', submission.id)

      return NextResponse.json(
        { error: 'Failed to create payroll entries', details: entriesError.message },
        { status: 500 }
      )
    }

    console.log('✅ Payroll entries created:', payrollEntries.length)

    // Generate formatted submission number for display
    const formatted_submission_number = `SUB-${submission.submission_number}`

    return NextResponse.json({
      success: true,
      submission_id: submission.id,
      submission_number: formatted_submission_number,
      message: 'Payroll submitted successfully'
    })

  } catch (error: any) {
    console.error('❌ API error:', error)
    return NextResponse.json(
      { error: 'Internal server error', details: error.message },
      { status: 500 }
    )
  }
}
